services:
  _defaults:
    autowire: true
    autoconfigure: true

  Symfony\Component\Filesystem\Filesystem:
    shared: false

  Saccas\JsonApiClientGenerator\:
    resource: '../JsonApiClientGenerator/'
    exclude: '../JsonApiClientGenerator/{DependencyInjection,Entity,Tests,Kernel.php}'

  Saccas\JsonApiClientGenerator\Command\GenerateCommand:
    public: true
